---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendesk-predictive-agent

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

commonLabels:
  app.kubernetes.io/name: opendesk-predictive-agent
  app.kubernetes.io/part-of: opendesk
  app.kubernetes.io/managed-by: kustomize

images:
  - name: 172.25.24.36:5001/predictive-agent
    newTag: v8.1-nix
